### PR TITLE
Improved handling of max step height on sloped terrain

### PR DESCRIPTION
**Pull request by haider8645**
Hello @chhtz,

here the PR for the change to handling of step height check on sloped terrain.

- [x] We would need to add a dependency to cgal in ugv installation instructions for this change

Best,
Haider

### CODE REVIEW

**Comment by haider8645** [comment]
@m0rsch1 after testing, please let us know if this branch solves the issue of the strange obstacles.

**Comment by m0rsch1** [comment]
@haider8645 This is a BIG improvement on the map quality and needs to be merged asap :1st_place_medal:
I would suggest, that you/we later perform a complete review of this library to even further improve this.

**Comment by m0rsch1** [comment]
Screenshot from 2024-11-20 16-50-46
Screenshot from 2024-11-20 16-50-06

**Comment by haider8645** [comment]
@chhtz has some ideas of improving the polygon intersection with the MLS. We could discuss that as the next step as one of the ways to improve the performance.

**Comment by haider8645** [comment]
I am now writing some tests so that we can improve the performance and also compare the time taken for the trav map expansion scaling with map size and number of collisions

**Comment by haider8645** [comment]
image

**Pull request merged**
